clear variables;
clc;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Load reference json file
fileID = fopen('D:\Downloads\RC17Games\2017-07-29_NomadZ\half1\170729-0901-Nao0338\game.json');
    reference_text = textscan(fileID,'%c');
fclose(fileID);
reference_json = jsondecode(reference_text{1});

% Load json file generated by classifier
fileID = fopen('D:\RoboCup\NaoTH-2015\Utils\MatlabDeepLearning\generated\result_CNN_rc17_augmented_8\half1-170729-0901-Nao0338-game.json');
    classifier_text = textscan(fileID,'%c');
fclose(fileID);
classifier_json = jsondecode(classifier_text{1});

% create sorted table of framenumbers and classifications
reference_frame_nums = [reference_json.ball; reference_json.noball];
reference_values = [ones(length(reference_json.ball),1); zeros(length(reference_json.noball),1)];
reference_table = table(reference_frame_nums, reference_values);
reference_table = sortrows(reference_table);

% create sorted table of framenumbers and classifications
classifier_frame_nums = [classifier_json.ball; classifier_json.noball];
classifier_values = [ones(length(classifier_json.ball),1); zeros(length(classifier_json.noball),1)];
classifier_table = table(classifier_frame_nums, classifier_values);
classifier_table = sortrows(classifier_table);

%
ref_test = transpose(reference_table.reference_values);
cls_test = transpose(classifier_table.classifier_values);
[c,cm,ind,per] = confusion(ref_test, cls_test);

% Noball is class 0 - Ball is class 1
% Recall = TP / TP + FN
Recall_Ball = cm(2,2)/ (cm(2,2) + cm(2,1))
Recall_NoBall = cm(1,1)/ (cm(1,1) + cm(1,2));

% Precision = TP / TP + FP
precision_Ball = cm(2,2) / (cm(2,2) + cm(1,2))
precision_NoBall = cm(1,1) / (cm(1,1) + cm(2,1));

plotconfusion(ref_test, cls_test);