#!/bin/bash

### set WIFI network, set to non-existing SSID to decativate
# usage: scripts/wep_wlan SSID KEY

SSID=$1
KEY=$2

echo $'network={
        ssid="'$SSID$'"
        key_mgmt=NONE
        wep_key0="'$KEY$'"
        wep_tx_keyidx=0
        priority=1
}' > /etc/wpa_supplicant/wpa_supplicant.conf

# restart the wlan0 interface
/etc/init.d/net.wlan0 restart

