version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true
  sonar-java:
    enabled: false
  sonar-python:
    enabled: true
exclude_patterns:
  - .git/
  - .gitlab/
  - .vscode/
  - Third-Party-Licenses/
  - NaoSCP/
  - NaoTHSoccer/
  - RobotControl/


