/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.naoth.rc.dialogs.panels;//ColorValueSlidersPanel

import java.awt.GridLayout;
import java.beans.PropertyChangeListener;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author claas
 */
public class ColorValueSlidersPanel extends javax.swing.JPanel 
{
  private HashMap<String, Integer> valueControls;
  
  private int onOffControlIdx;
  /**
   * Creates new form ColorValueSlidersPanel
   */
  public ColorValueSlidersPanel() 
  {
    initComponents();
    
    GridLayout layout = new GridLayout(10, 1);
    this.setLayout(layout); 
    valueControls = new HashMap<String, Integer>();
  }  

  public void addControl(String objectName, String name, int value, PropertyChangeListener listener, boolean showPixels)
  {    
    if(this.getComponentCount() == 0)
    {
      ColorPixelOnOffControl pixelOnOffControl = new ColorPixelOnOffControl(objectName, listener, showPixels);
      this.add(pixelOnOffControl, -1);
      onOffControlIdx = this.getComponentCount() - 1;
    }
    
    if(!valueControls.containsKey(name))
    {
      ColorValueControl control = new ColorValueControl(objectName, name, listener);
      this.add(control, -1);
      int idx = this.getComponentCount() - 1;
      valueControls.put(name, idx);
      this.validate();
    }    
    setControlValue(name, value);
    //this.validate();
  }
  
  public void setControlValue(String name, int value)
  {
    if(valueControls.containsKey(name))
    {
      ColorValueControl control = (ColorValueControl) this.getComponent(valueControls.get(name).intValue());
      control.setValue(value);
    }
  }
          
  public String[][] getControlValues()
  {
    String[][] valueString = new String[valueControls.size()][2];
    int idx = 0;
    for(Map.Entry<String, Integer> entry : valueControls.entrySet())
    {
      ColorValueControl control = (ColorValueControl) this.getComponent(entry.getValue());
      valueString[idx][0] = entry.getKey();
      valueString[idx][1] = String.valueOf(control.getValue());
      idx++;
    }
    return valueString;
  }
      
  public boolean showColoredPixels()
  {
    ColorPixelOnOffControl pixelOnOffControl = (ColorPixelOnOffControl) this.getComponent(onOffControlIdx);
    return pixelOnOffControl.showColoredPixels();
  }
            
  @Override
  public void setEnabled(boolean value) 
  {
    for(Map.Entry<String, Integer> entry : valueControls.entrySet())
    {
      ColorValueControl control = (ColorValueControl) this.getComponent(entry.getValue());
      control.setEnabled(value);
    }
  }
  
  public void removeControls()
  {
    if(this.getComponentCount() > 0)
    {
      for(Map.Entry<String, Integer> entry : valueControls.entrySet())
      {
        ColorValueControl control = (ColorValueControl) this.getComponent(entry.getValue());
        PropertyChangeListener[] propListeners = control.getPropertyChangeListeners();
        for(PropertyChangeListener propListener: propListeners)
        {
          control.removePropertyChangeListener(propListener);
        }
      }
      ColorPixelOnOffControl pixelOnOffControl = (ColorPixelOnOffControl) this.getComponent(onOffControlIdx);
      PropertyChangeListener[] propListeners = pixelOnOffControl.getPropertyChangeListeners();
      for(PropertyChangeListener propListener: propListeners)
      {
        pixelOnOffControl.removePropertyChangeListener(propListener);
      }
    }
    this.removeAll();
    valueControls.clear();
    this.repaint();
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(51, 51, 51)));
        setMaximumSize(new java.awt.Dimension(260, 32767));
        setMinimumSize(new java.awt.Dimension(260, 480));
        setPreferredSize(new java.awt.Dimension(260, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31996, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
