/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImagePanel.java
 *
 * Created on 07.03.2013, 19:27:12
 */
package de.naoth.rc.dialogs.panels;

import de.naoth.rc.dialogs.drawings.Drawable;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.util.ArrayList;

/**
 *
 * @author admin
 */
public class ImagePanel extends javax.swing.JPanel
{
    private Image backgroundImage;
    private boolean keepAspectRatio;
    private boolean stretchImage;
    private final ArrayList<Drawable> drawigs = new ArrayList<Drawable>();
    
    /** Creates new form ImagePanel */
    public ImagePanel()
    {
        initComponents();
        
        this.keepAspectRatio = true;
        this.stretchImage = true;
    }
    
    
    public void setImage(Image image)
    {
      this.backgroundImage = image;
      //this.setSize(imagePanel.getSize());
      this.repaint();
    }

    public void setKeepAspectRatio(boolean value)
    {
      this.keepAspectRatio = value;
    }

    public void setStretchImage(boolean value)
    {
      this.stretchImage = value;
    }

    public Image getImage()
    {
      return this.backgroundImage;
    }

    public ArrayList<Drawable> getDrawingList()
    {
      return this.drawigs;
    }

    @Override
    public void paint(Graphics g)
    {
        Graphics2D g2d = (Graphics2D) g;

        if (backgroundImage == null) {
            return;
        }
      
        double hPanel = (double) getHeight() - 2;
        double wPanel = (double) getWidth() - 2;

        double hImg = (double) backgroundImage.getHeight(this);
        double wImg = (double) backgroundImage.getWidth(this);

        double posX = 0.0;
        double posY = 0.0;

        double ratioH = hPanel / hImg;
        double ratioW = wPanel / wImg;

        if (!this.stretchImage)
        {
          posX = Math.round((wPanel - wImg) * 0.5);
          posY = Math.round((hPanel - hImg) * 0.5);
          ratioH = 1.0;
          ratioW = 1.0;
        }
        else
        {
          if (this.keepAspectRatio)
          {
            double scale = Math.min(hPanel / hImg, wPanel / wImg);
            posX = Math.round((wPanel - scale * wImg) * 0.5);
            posY = Math.round((hPanel - scale * hImg) * 0.5);
            ratioH = scale;
            ratioW = scale;
          }
        }

        g2d.translate((posX + 1), (posY + 1));
        g2d.scale(ratioW, ratioH);

        g2d.drawImage(backgroundImage, 0, 0, (int) wImg, (int) hImg, this);

        for (Drawable d : drawigs)
        {
          d.draw(g2d);
        }

        // transform the drawing-pane back (nessesary to draw the other components correct)
        g2d.scale(1.0, 1.0);
        g2d.translate(-(posX + 1), -(posY + 1));

    }//end paint

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
