#!/bin/bash

PID="/tmp/cognition.pid"

case "$1" in
  start)
    if [ -f "$PID" ]; then
      OLDPID=`cat /tmp/cognition.pid`
      echo "old pid is $OLDPID"
      kill -0 $OLDPID
      if [ "$?" -eq 0 ]; then
        echo "NaoTH cognition already started, use stop first"
        exit 1
      else
        echo "removing stalled $PID"
        rm "$PID"
      fi
    fi

    echo "starting naoth cognition process"
    cd /home/nao/naoqi/

    if [ nao = `whoami` ]; then
      nohup /etc/init.d/cognition-common 2>&1 | logger &
    else
      su -c 'nohup /etc/init.d/cognition-common 2>&1 | logger &' nao
    fi
    ;;
  stop)
    if [ ! -f "$PID" ]; then
      echo "NaoTH Cognition not started"
      exit 2
    fi
    OLDPID=`cat /tmp/cognition.pid`
    echo "killing naoth cognition processes $OLDPID"
    kill $OLDPID
    while [ -d "/proc/$OLDPID" ]
    do
      sleep 1
    done
    rm $PID

    ;;
  restart)
    $0 stop
    sleep 5
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/naoqi {start|stop|restart}"
    exit 1
    ;;

esac

exit 0
