package de.naoth.rc.components.preferences;

/**
 *
 * @author Philipp Strobel <philippstrobel@posteo.de>
 */
public class PreferencesSpinner extends javax.swing.JPanel implements PreferencesField {

    /**
     * Creates new form integer spinner
     * @param title
     * @param value
     */
    public PreferencesSpinner(String title, int value) {
        initComponents();
        
        this.label.setText(title);
        this.spinner.setValue(value);
    }
    
    @Override
    public String getPreferenceName() {
        return getName();
    }
    
    @Override
    public String getPreferenceValue() {
        return String.valueOf(spinner.getValue());
    }
    
    @Override
    public void setPreferenceValue(String value) {
        if(value != null) {
            spinner.setValue(Integer.parseInt(value));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        spinner = new javax.swing.JSpinner();

        setMaximumSize(new java.awt.Dimension(2147483647, 40));
        setLayout(new java.awt.BorderLayout());

        label.setLabelFor(spinner);
        label.setText("Name");
        add(label, java.awt.BorderLayout.NORTH);

        spinner.setModel(new javax.swing.SpinnerNumberModel());
        add(spinner, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables
}
