plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.jcraft:jsch:0.1.55'
}

// Define the default tasks
defaultTasks 'run'

// Set the project version and Java compatibility versions
version = '1.1'
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

// Configure the application plugin
application {
    mainClass = 'Main'
    executableDir = '' // do not create a "bin" directory in install/zip
    applicationName = 'naoscp' // set the startscripts to lower case
}

// Set source directories and disable unnecessary directories
sourceSets {
    main {
        java.srcDirs = ['src']
        resources.srcDirs = []
    }
    test {
        java.srcDirs = []
        resources.srcDirs = []
    }
}

// "install" the resulting application to the "dist" directory (mimic the old behavior)
installDist {
    destinationDir = file("$projectDir/dist")
}

// Disable TAR generation
distTar {
    enabled = false
}

// Ensure "installDist" task is executed after build
build {
    finalizedBy installDist
}

// Ensure the "dist" directory is also cleaned (needs to be done separately, since we're moved it out of the build directory)
tasks.register('cleanDist', Delete) {
    delete "$projectDir/dist"
}
clean {
    finalizedBy tasks.cleanDist
}

// Create a manifest for the JAR
jar {
    manifest {
        attributes(
            'Class-Path': sourceSets.main.runtimeClasspath.files.collect { it.name }.join(' '),
            'Main-Class': application.mainClass
        )
    }
}