#!/bin/bash
# ! #/sbin/runscript

description=""

depends(){
    need set_dev_video
    after set_dev_video
    after naoqi
}

PID="/tmp/cognition.pid"

start(){
    if [ -f "$PID" ]; then
      OLDPID=`cat /tmp/cognition.pid`
      echo "old pid is $OLDPID"
      kill -0 $OLDPID
      if [ "$?" -eq 0 ]; then
        echo "NaoTH cognition already started, use stop first"
        exit 1
      else
        echo "removing stalled $PID"
        rm "$PID"
      fi
    fi

    echo "starting naoth cognition process"
    cd /home/nao/naoqi/

    if [ nao = `whoami` ]; then
      nohup /etc/init.d/cognition-common 2>&1 | logger &
    else
      su -c 'nohup /etc/init.d/cognition-common 2>&1 | logger &' nao
    fi
}

stop(){
    if [ ! -f "$PID" ]; then
      echo "NaoTH Cognition not started"
      exit 2
    fi
    OLDPID=`cat /tmp/cognition.pid`
    echo "killing naoth cognition processes $OLDPID"
    kill $OLDPID
    rm $PID

}

restart(){
    $0 stop
    $0 start
}


