package de.naoth.rc.dialogs;

import de.naoth.rc.core.dialog.AbstractDialog;
import de.naoth.rc.core.dialog.DialogPlugin;
import de.naoth.rc.RobotControl;
import de.naoth.rc.core.dialog.RCDialog;
import de.naoth.rc.dataformats.JanusImage;
import de.naoth.rc.drawings.Canvas;
import de.naoth.rc.drawings.Drawable;
import de.naoth.rc.drawings.DrawingCollection;
import de.naoth.rc.drawings.DrawingOnImage;
import de.naoth.rc.drawings.DrawingsContainer;
import de.naoth.rc.manager.DebugDrawingManager;
import de.naoth.rc.manager.ImageManagerBottom;
import de.naoth.rc.core.manager.ObjectListener;
import de.naoth.rc.dataformats.ImageConversions;
import de.naoth.rc.logmanager.BlackBoard;
import de.naoth.rc.logmanager.LogDataFrame;
import de.naoth.rc.logmanager.LogFileEventManager;
import de.naoth.rc.logmanager.LogFrameListener;
import de.naoth.rc.manager.ImageManagerBottomImpl;
import de.naoth.rc.manager.ImageManagerTop;
import de.naoth.rc.manager.ImageManagerTopImpl;
import java.awt.Color;
import java.awt.Graphics2D;
import net.xeoh.plugins.base.annotations.PluginImplementation;
import net.xeoh.plugins.base.annotations.injections.InjectPlugin;

/**
 *
 * @author  Thomas
 * @author  Heinrich
 */
public class ImageViewer extends AbstractDialog
{
   
  @RCDialog(category = RCDialog.Category.View, name = "Image")
  @PluginImplementation
  public static class Plugin extends DialogPlugin<ImageViewer> {
    @InjectPlugin
    public static RobotControl parent;
    @InjectPlugin
    public static ImageManagerBottom imageManagerBottom;
    @InjectPlugin
    public static ImageManagerTop imageManagerTop;
    @InjectPlugin
    public static DebugDrawingManager debugDrawingManager;
    @InjectPlugin
    public static LogFileEventManager logFileEventManager;
  }//end Plugin

  private Drawable fadeOutBox = null;
  
  // listeners
  ImageListenerBottom imageListenerBottom;
  ImageListenerTop imageListenerTop;
  DrawingsListener drawingsListener;

  // watchers for the image update speed
  private final FPS fpsTop = new FPS();
  private final FPS fpsBottom = new FPS();
  
  public ImageViewer()
  {
    initComponents();
    
    this.imageCanvasBottom.setVisible(false);
    this.imageCanvasTop.setVisible(false);
    
    this.drawingsListener = new DrawingsListener();
    this.imageListenerBottom = new ImageListenerBottom();
    this.imageListenerTop = new ImageListenerTop();
    
    Plugin.logFileEventManager.addListener(new LogBehaviorListener());
    
    // JPEG by default
    btRAW.setSelected(false);
    Plugin.imageManagerBottom.setFormat(ImageConversions.Format.JPEG);
    Plugin.imageManagerTop.setFormat(ImageConversions.Format.JPEG);
  }
  
  private class LogBehaviorListener implements LogFrameListener
  {
    @Override
    public void newFrame(BlackBoard b) 
    {
        LogDataFrame f = b.get(btRAW.isSelected()?"Image":"ImageJPEG");
        if(f != null) {
          ImageManagerBottomImpl im = new ImageManagerBottomImpl();
          JanusImage janusImage = im.convertByteArrayToType(f.getData());
          
          ImageViewer.this.imageCanvasBottom.setImage(janusImage.getRGB());
          ImageViewer.this.imageCanvasBottom.repaint();
        }
        
        f = b.get(btRAW.isSelected()?"ImageTop":"ImageJPEGTop");
        if(f != null) {
          ImageManagerTopImpl im = new ImageManagerTopImpl();
          JanusImage janusImage = im.convertByteArrayToType(f.getData());
          
          ImageViewer.this.imageCanvasTop.setImage(janusImage.getRGB());
          ImageViewer.this.imageCanvasTop.repaint();
        }
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        imageCanvasTop = new de.naoth.rc.components.ImagePanel();
        imageCanvasBottom = new de.naoth.rc.components.ImagePanel();
        jToolBar1 = new javax.swing.JToolBar();
        btReceiveImagesTop = new javax.swing.JToggleButton();
        btReceiveImagesBottom = new javax.swing.JToggleButton();
        btReceiveDrawings = new javax.swing.JToggleButton();
        btRAW = new javax.swing.JToggleButton();
        cbStretch = new javax.swing.JCheckBox();
        cbFadeOut = new javax.swing.JCheckBox();
        btHorizontal = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabelResolution = new javax.swing.JLabel();
        jLabelFPSBottom = new javax.swing.JLabel();
        jLabelFPSTop = new javax.swing.JLabel();

        imagePanel.setBackground(java.awt.Color.gray);
        imagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.darkGray));
        imagePanel.setPreferredSize(new java.awt.Dimension(320, 240));
        imagePanel.setLayout(new javax.swing.BoxLayout(imagePanel, javax.swing.BoxLayout.PAGE_AXIS));

        imageCanvasTop.setBackground(java.awt.Color.gray);
        imageCanvasTop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imageCanvasTop.setOpaque(false);

        javax.swing.GroupLayout imageCanvasTopLayout = new javax.swing.GroupLayout(imageCanvasTop);
        imageCanvasTop.setLayout(imageCanvasTopLayout);
        imageCanvasTopLayout.setHorizontalGroup(
            imageCanvasTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        imageCanvasTopLayout.setVerticalGroup(
            imageCanvasTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        imagePanel.add(imageCanvasTop);

        imageCanvasBottom.setBackground(java.awt.Color.gray);
        imageCanvasBottom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imageCanvasBottom.setOpaque(false);

        javax.swing.GroupLayout imageCanvasBottomLayout = new javax.swing.GroupLayout(imageCanvasBottom);
        imageCanvasBottom.setLayout(imageCanvasBottomLayout);
        imageCanvasBottomLayout.setHorizontalGroup(
            imageCanvasBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        imageCanvasBottomLayout.setVerticalGroup(
            imageCanvasBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        imagePanel.add(imageCanvasBottom);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btReceiveImagesTop.setText("Receive Top");
        btReceiveImagesTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceiveImagesTopActionPerformed(evt);
            }
        });
        jToolBar1.add(btReceiveImagesTop);

        btReceiveImagesBottom.setText("Receive Bottom");
        btReceiveImagesBottom.setFocusable(false);
        btReceiveImagesBottom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReceiveImagesBottom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReceiveImagesBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceiveImagesBottomActionPerformed(evt);
            }
        });
        jToolBar1.add(btReceiveImagesBottom);

        btReceiveDrawings.setText("Receive Drawings");
        btReceiveDrawings.setFocusable(false);
        btReceiveDrawings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReceiveDrawings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReceiveDrawings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceiveDrawingsActionPerformed(evt);
            }
        });
        jToolBar1.add(btReceiveDrawings);

        btRAW.setText("RAW");
        btRAW.setFocusable(false);
        btRAW.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRAW.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btRAW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRAWActionPerformed(evt);
            }
        });
        jToolBar1.add(btRAW);

        cbStretch.setSelected(true);
        cbStretch.setText("stretch image");
        cbStretch.setFocusable(false);
        cbStretch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        cbStretch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cbStretch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStretchActionPerformed(evt);
            }
        });
        jToolBar1.add(cbStretch);

        cbFadeOut.setText("Fade Out");
        cbFadeOut.setToolTipText("Fades out the image so the drawings can be seen better.");
        cbFadeOut.setFocusable(false);
        cbFadeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFadeOutActionPerformed(evt);
            }
        });
        jToolBar1.add(cbFadeOut);

        btHorizontal.setText("Horizontal");
        btHorizontal.setFocusable(false);
        btHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHorizontalActionPerformed(evt);
            }
        });
        jToolBar1.add(btHorizontal);

        jLabelResolution.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabelResolution.setText("- x - ");
        jPanel1.add(jLabelResolution);

        jLabelFPSBottom.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabelFPSBottom.setText("FPS Bottom");
        jPanel1.add(jLabelFPSBottom);

        jLabelFPSTop.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jLabelFPSTop.setText("FPS Top");
        jPanel1.add(jLabelFPSTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
  private void btReceiveImagesTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceiveImagesTopActionPerformed

    if (!Plugin.parent.checkConnected()) {
      dispose();
      return;
    }
      
    if (this.btReceiveImagesTop.isSelected())
    {
     this.imageCanvasTop.setVisible(true);
     Plugin.imageManagerTop.addListener(this.imageListenerTop);
    }
    else
    {
      this.imageCanvasTop.setVisible(false);
      Plugin.imageManagerTop.removeListener(this.imageListenerTop);
    }

  }//GEN-LAST:event_btReceiveImagesTopActionPerformed

  private void cbStretchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStretchActionPerformed
    this.imageCanvasBottom.setStretchImage(this.cbStretch.isSelected());
    this.imageCanvasTop.setStretchImage(this.cbStretch.isSelected());
  }//GEN-LAST:event_cbStretchActionPerformed

  private void btReceiveDrawingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceiveDrawingsActionPerformed
      if (!Plugin.parent.checkConnected()) {
        dispose();
        return;
      }
      
      if (this.btReceiveDrawings.isSelected()) {
        Plugin.debugDrawingManager.addListener(this.drawingsListener);
        this.imageCanvasBottom.setShowDrawings(true);
        this.imageCanvasTop.setShowDrawings(true);
      } else {
        Plugin.debugDrawingManager.removeListener(this.drawingsListener);
        this.imageCanvasBottom.setShowDrawings(false);
        this.imageCanvasTop.setShowDrawings(false);
      }
  }//GEN-LAST:event_btReceiveDrawingsActionPerformed

  private void btReceiveImagesBottomActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btReceiveImagesBottomActionPerformed
  {//GEN-HEADEREND:event_btReceiveImagesBottomActionPerformed
    
    if (!Plugin.parent.checkConnected()) {
        dispose();
        return;
    }
      
    if (btReceiveImagesBottom.isSelected())
    {
      this.imageCanvasBottom.setVisible(true);
      Plugin.imageManagerBottom.addListener(this.imageListenerBottom);
    }
    else
    {
      this.imageCanvasBottom.setVisible(false);
      Plugin.imageManagerBottom.removeListener(this.imageListenerBottom);
    }
    
  }//GEN-LAST:event_btReceiveImagesBottomActionPerformed

    private void cbFadeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFadeOutActionPerformed
        if(this.cbFadeOut.isSelected()) {
            this.fadeOutBox = new ImageOverlayDrawing(640, 480, new Color(255,255,255,128));
        } else {
            this.fadeOutBox = null;
        }
    }//GEN-LAST:event_cbFadeOutActionPerformed

    private void btHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHorizontalActionPerformed
        if(btHorizontal.isSelected()) {
            imagePanel.setLayout(new javax.swing.BoxLayout(imagePanel, javax.swing.BoxLayout.X_AXIS));
        } else {
            imagePanel.setLayout(new javax.swing.BoxLayout(imagePanel, javax.swing.BoxLayout.Y_AXIS));
        }
    }//GEN-LAST:event_btHorizontalActionPerformed

    private void btRAWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRAWActionPerformed
        if(btRAW.isSelected()) {
            Plugin.imageManagerBottom.setFormat(ImageConversions.Format.RAW);
            Plugin.imageManagerTop.setFormat(ImageConversions.Format.RAW);
        } else {
            Plugin.imageManagerBottom.setFormat(ImageConversions.Format.JPEG);
            Plugin.imageManagerTop.setFormat(ImageConversions.Format.JPEG);
        }
    }//GEN-LAST:event_btRAWActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btHorizontal;
    private javax.swing.JToggleButton btRAW;
    private javax.swing.JToggleButton btReceiveDrawings;
    private javax.swing.JToggleButton btReceiveImagesBottom;
    private javax.swing.JToggleButton btReceiveImagesTop;
    private javax.swing.JCheckBox cbFadeOut;
    private javax.swing.JCheckBox cbStretch;
    private de.naoth.rc.components.ImagePanel imageCanvasBottom;
    private de.naoth.rc.components.ImagePanel imageCanvasTop;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabelFPSBottom;
    private javax.swing.JLabel jLabelFPSTop;
    private javax.swing.JLabel jLabelResolution;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables


  private void updateResolution(int x, int y)
  {
    this.jLabelResolution.setText(x + "x" + y);
  }
  
  private class FPS {
      private long timestampOfTheLastImage;
      private double fps = 0.0;
      private final double filter = 0.9;
      
      private void update()
    {
      long currentTime = System.currentTimeMillis();
      double v = 1000.0 / ((double) (currentTime - this.timestampOfTheLastImage));
      fps = fps*filter + v*(1.0-filter);
      this.timestampOfTheLastImage = currentTime;
    }
      
      public double getFPS() {
          return fps;
      } 
  }

  private void updateFPS()
  {
    this.jLabelFPSTop.setText(String.format(" T: %2.1f fps ", fpsTop.getFPS()));
    this.jLabelFPSBottom.setText(String.format(" B: %2.1f fps ", fpsBottom.getFPS()));
  }

  class DrawingsListener implements ObjectListener<DrawingsContainer>
  {
    @Override
    public void newObjectReceived(DrawingsContainer objectList)
    {
      if (objectList != null)
      {
        ImageViewer.this.imageCanvasBottom.getDrawingList().clear();
        ImageViewer.this.imageCanvasTop.getDrawingList().clear();
        
        // Deprecated
        DrawingCollection drawingCollection = objectList.get(DrawingOnImage.class);
        if (drawingCollection != null) {
          ImageViewer.this.imageCanvasBottom.getDrawingList().add(drawingCollection);
        }
        
        if(ImageViewer.this.fadeOutBox != null) {
            ImageViewer.this.imageCanvasTop.getDrawingList().add(fadeOutBox);
            ImageViewer.this.imageCanvasBottom.getDrawingList().add(fadeOutBox);
        }
        
        Canvas canvasTop = objectList.get("ImageTop");
        if (canvasTop != null) {
          ImageViewer.this.imageCanvasTop.getDrawingList().add(canvasTop);
        }
        
        Canvas canvasBottom = objectList.get("ImageBottom");
        if (canvasBottom != null) {
          ImageViewer.this.imageCanvasBottom.getDrawingList().add(canvasBottom);
        }
        
        repaint();
      }
    }//end newObjectReceived
    
    @Override
    public void errorOccured(String cause)
    {
      ImageViewer.this.btReceiveDrawings.setSelected(false);
      ImageViewer.Plugin.debugDrawingManager.removeListener(this);
    }
  }//end class DrawingsListener

  private class ImageListenerBottom implements ObjectListener<JanusImage>
  {
    @Override
    public void newObjectReceived(JanusImage object)
    {
      if(object == null) return;
      ImageViewer.this.imageCanvasBottom.setImage(object.getRGB());
      ImageViewer.this.imageCanvasBottom.repaint();

      updateResolution(object.getRGB().getWidth(), object.getRGB().getHeight());
      
      fpsBottom.update();
      updateFPS();
    }

    @Override
    public void errorOccured(String cause)
    {
      ImageViewer.this.btReceiveImagesBottom.setSelected(false);
      ImageViewer.this.imageCanvasBottom.setVisible(false);
      ImageViewer.Plugin.imageManagerBottom.removeListener(this);
    }
  }//end ImageListener
  
  private class ImageListenerTop implements ObjectListener<JanusImage>
  {
    @Override
    public void newObjectReceived(JanusImage object)
    {
      if(object == null) return;
      ImageViewer.this.imageCanvasTop.setImage(object.getRGB());
      ImageViewer.this.imageCanvasTop.repaint();
      
      fpsTop.update();
      updateFPS();
    }

    @Override
    public void errorOccured(String cause)
    {
      ImageViewer.this.btReceiveImagesTop.setSelected(false);
      ImageViewer.this.imageCanvasTop.setVisible(false);
      ImageViewer.Plugin.imageManagerTop.removeListener(this);
    }
  }//end SecondaryImageListener
  
  class ImageOverlayDrawing implements Drawable
  {
    private final Color color;
    private final int width;
    private final int height;
    
    ImageOverlayDrawing(int width, int height, Color color) {
        this.width = width;
        this.height = height;
        this.color = color;
    }
            
    @Override
    public void draw(Graphics2D g2d) {
        g2d.setColor(color);
        g2d.fillRect(0, 0, width, height);
    }
  }

  @Override
  public void dispose()
  {
    Plugin.imageManagerBottom.removeListener(this.imageListenerBottom);
    Plugin.debugDrawingManager.removeListener(this.drawingsListener);
    this.btReceiveImagesTop.setSelected(false);
    this.btReceiveImagesBottom.setSelected(false);
    this.btReceiveDrawings.setSelected(false);
  }
}//end class ImageViewer

