[stella_config]
model_name = "fy_1500_new"
metrics = ["ClassificationMetric", "IoU"]
trainings_data = "tk03_combined_detection.pkl"
batch_size = 256
epochs = 1
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

output_path = "models"
##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false
#
model_path = "fy_1500_new_tk03_combined_detection.h5"

[config2]
model_name = "fy_1500_old"
#metrics = ["ClassificationMetric", "IoU"]
trainings_data = "tk03_combined_detection.pkl"
batch_size = 256
epochs = 1
proceed = false  # proceed=true will be ignored if model_name is set  # TODO think about what behavior is the least surprising

output_path = "models"
##### compile only options
# Switch between debug and production build. The debug build creates code for running the network multiple times and provides timing measurements in the end.
compile_debug = false
# TODO this can be dynamically calculated by the compiler
model_path = "fy_1500_old_tk03_combined_detection.h5"