#!/usr/bin/env bash

#check if root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

#templates
minimal=autoload_minimal.ini
full=autoload_full.ini

template_path=/etc/naoqi/templates/
target=/etc/naoqi/autoload.ini

############## MAIN ###################
function mainFunc() {
  cp $target $target.bak
  cp $template_path$1 $target
}

usage() {
  echo -n "
Usage: $0 [OPTION] [TEMPLATE]

 Templates:
  minimal           Set the minimal list of modules loaded in NaoQi core process required by naoth
  full              Set the full list of modules loaded in NaoQi core process

 Options:
  -d, --display     Display template and exit
  -h, --help        Display this help and exit

 Example:
  $0 minimal

"
  exit
}

# Parse arguments
option=None

if [ "$2" != "" ]; then
  case $2 in
    minimal) option=$minimal ;;
    full) option=$full ;;
    *) echo "invalid template: '$2'."; usage ;;
  esac

  case $1 in
    -d|--display) cat $template_path$option; exit 0;;
    -h|--help) usage ;;
    *) echo "invalid option: '$1'."; usage ;;
  esac

elif [ "$1" != "" ]; then
  case $1 in
    -h|--help) usage ;;
    minimal) option=$minimal ;;
    full) option=$full ;;
    *) echo "invalid template: '$1'."; usage ;;
  esac
else
  usage
fi

# Run script
mainFunc $option
