/**
 * @file main.cpp
 *
 * @author <a href="mailto:critter@informatik.hu-berlin.de">CNR</a>
 */

#include "LolaAdaptor.h"

#include <csignal>
#include <unistd.h>
#include <chrono>
#include <sys/stat.h>

using namespace naoth;
using namespace std;

// std::atomic_int framesSinceCognitionLastSeen;
std::atomic_bool running;
std::atomic_bool already_got_signal;
bool stopping;

#define TO_STRING_INT(x) #x
#define TO_STRING(x) TO_STRING_INT(x)

std::string getSignalDescription(int sigid)
{
  switch (sigid)
  {
    case SIGABRT:
      return "Caught Signal Abort: Abnormal termination, such as is initiated by the abort function.";
    case SIGFPE:
      return "Caught Signal Floating-Point Exception: Erroneous arithmetic operation, such as zero divide or an operation resulting in overflow (not necessarily with a floating-point operation).";
    case SIGILL:
      return "Caught Signal Illegal Instruction: Invalid function image, such as an illegal instruction. This is generally due to a corruption in the code or to an attempt to execute data.";
    case SIGINT:
      return "Caught Signal Interrupt: Interactive attention signal. Generally generated by the application user.";
    case SIGSEGV:
      return "Caught Signal Segmentation Violation: Invalid access to storage: When a program tries to read or write outside the memory it has allocated.";
    case SIGTERM:
      return "Caught Signal Terminate: Termination request sent to program.";
    default:
      return "Caught unknown signal.";
  }
}


// handle signals to stop the binary
void got_signal(int sigid)
{
  std::cout << getSignalDescription(sigid) << std::endl;

  // notify all threads to stop
  running = false;

  if(sigid == SIGTERM || sigid == SIGINT) // graceful stop
  {
    std::cout << "shutdown requested by kill signal " << sigid << std::endl;
    
    if (already_got_signal) {
      std::cout << "WARNING: received repeated kill signals. Graceful stop was not possible. Will kill." << std::endl;
    } else {
      // remember that we got a signal in case we don't manage to stop the binary gracefully
      already_got_signal = true;
      // if(sigid == SIGINT) 
      // {
      //   system("paplay /opt/aldebaran/share/naoqi/wav/shutdown.wav");
      // }

    // stop signal handling for now and give the binary time to stop gracefully
      return;
    }
  } 
  else if(sigid == SIGSEGV) // segmentation fault
  {
    std::cerr << "SEGMENTATION FAULT" << std::endl;
    
    std::cout << "dumping traces" << std::endl;
    Trace::getInstance().dump();
    //StopwatchManager::getInstance().dump("cognition");

    std::cout << "syncing file system..." ;
    sync();
    std::cout << " finished." << std::endl;
  } 

  // set the default handler for the signal and forward the signal
  std::signal(sigid, SIG_DFL);
  std::raise(sigid);

}//end got_signal

bool fileExists (const std::string& filename) {
  struct stat buffer;   
  return (stat (filename.c_str(), &buffer) == 0); 
}

int main(int /*argc*/, char **/*argv[]*/)
{
  std::cout << "=========================================="  << std::endl;
  std::cout << "LoalAdaptor compiled on: " << __DATE__ << " at " << __TIME__ << std::endl;

  system("paplay /home/nao/Media/bip_power_on.wav");

  #ifdef REVISION
  std::cout << "Revision number: " << TO_STRING(REVISION) << std::endl;
  #endif
  #ifdef USER_NAME
  std::cout << "Owner: " << TO_STRING(USER_NAME) << std::endl;
  #endif
  #ifdef BRANCH_PATH
  std::cout << "Branch path: " << TO_STRING(BRANCH_PATH) << std::endl;
  #endif
  std::cout << "==========================================\n"  << std::endl;

  // react on "kill" and segmentation fault:
  // Signal     Value     Action   Comment
  // --------------------------------------------------------
  // SIGSEGV      11       Core    Invalid memory reference
  // SIGINT        2       Term    Interrupt from keyboard
  // SIGQUIT       3       Core    Quit from keyboard
  // SIGKILL       9       Term    Kill signal
  //

  // from http://www.cplusplus.com/reference/csignal/signal/:
  // SIGABRT	(Signal Abort)                    Abnormal termination, such as is initiated by the abort function.
  // SIGFPE	  (Signal Floating-Point Exception) Erroneous arithmetic operation, such as zero divide or an operation resulting in overflow (not necessarily with a floating-point operation).
  // SIGILL	  (Signal Illegal Instruction)      Invalid function image, such as an illegal instruction. This is generally due to a corruption in the code or to an attempt to execute data.
  // SIGINT	  (Signal Interrupt)                Interactive attention signal. Generally generated by the application user.
  // SIGSEGV	(Signal Segmentation Violation)   Invalid access to storage: When a program tries to read or write outside the memory it has allocated.
  // SIGTERM	(Signal Terminate)                Termination request sent to program.

  // important
  std::signal(SIGTERM, got_signal);
  std::signal(SIGINT,  got_signal);
  std::signal(SIGSEGV, got_signal);

  std::signal(SIGABRT, got_signal);
  std::signal(SIGFPE,  got_signal);
  std::signal(SIGILL,  got_signal);

  // create the controller
  if(fileExists("/usr/bin/lola") || fileExists("/opt/aldebaran/bin/lola"))
  {
    LolaAdaptor theLolaAdaptor;

    // try to start lola
    theLolaAdaptor.start();
    running = true;
    stopping = false;

    while(!stopping && theLolaAdaptor.isRunning())
    {
      if(!running && !stopping)
      {
        system("killall naoth");
        sleep(5);
        stopping = true;
      }
      std::this_thread::sleep_for(std::chrono::milliseconds(125));
    }
  }

  return 0;
}//end main
