// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "commontypes.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace naothmessages {

namespace {

const ::google::protobuf::Descriptor* DoubleVector_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DoubleVector_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_commontypes_2eproto() {
  protobuf_AddDesc_commontypes_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "commontypes.proto");
  GOOGLE_CHECK(file != NULL);
  DoubleVector_descriptor_ = file->message_type(0);
  static const int DoubleVector_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DoubleVector, v_),
  };
  DoubleVector_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DoubleVector_descriptor_,
      DoubleVector::default_instance_,
      DoubleVector_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DoubleVector, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DoubleVector, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DoubleVector));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_commontypes_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DoubleVector_descriptor_, &DoubleVector::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_commontypes_2eproto() {
  delete DoubleVector::default_instance_;
  delete DoubleVector_reflection_;
}

void protobuf_AddDesc_commontypes_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021commontypes.proto\022\rnaothmessages\"\031\n\014Do"
    "ubleVector\022\t\n\001v\030\001 \003(\001B)\n\'de.hu_berlin.in"
    "formatik.ki.nao.messages", 104);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "commontypes.proto", &protobuf_RegisterTypes);
  DoubleVector::default_instance_ = new DoubleVector();
  DoubleVector::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_commontypes_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_commontypes_2eproto {
  StaticDescriptorInitializer_commontypes_2eproto() {
    protobuf_AddDesc_commontypes_2eproto();
  }
} static_descriptor_initializer_commontypes_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int DoubleVector::kVFieldNumber;
#endif  // !_MSC_VER

DoubleVector::DoubleVector()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DoubleVector::InitAsDefaultInstance() {
}

DoubleVector::DoubleVector(const DoubleVector& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DoubleVector::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DoubleVector::~DoubleVector() {
  SharedDtor();
}

void DoubleVector::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DoubleVector::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DoubleVector::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DoubleVector_descriptor_;
}

const DoubleVector& DoubleVector::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_commontypes_2eproto();  return *default_instance_;
}

DoubleVector* DoubleVector::default_instance_ = NULL;

DoubleVector* DoubleVector::New() const {
  return new DoubleVector;
}

void DoubleVector::Clear() {
  v_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DoubleVector::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated double v = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_v:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 9, input, this->mutable_v())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_v())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(9)) goto parse_v;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DoubleVector::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated double v = 1;
  for (int i = 0; i < this->v_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(
      1, this->v(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DoubleVector::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated double v = 1;
  for (int i = 0; i < this->v_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleToArray(1, this->v(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DoubleVector::ByteSize() const {
  int total_size = 0;
  
  // repeated double v = 1;
  {
    int data_size = 0;
    data_size = 8 * this->v_size();
    total_size += 1 * this->v_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DoubleVector::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DoubleVector* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DoubleVector*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DoubleVector::MergeFrom(const DoubleVector& from) {
  GOOGLE_CHECK_NE(&from, this);
  v_.MergeFrom(from.v_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DoubleVector::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DoubleVector::CopyFrom(const DoubleVector& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DoubleVector::IsInitialized() const {
  
  return true;
}

void DoubleVector::Swap(DoubleVector* other) {
  if (other != this) {
    v_.Swap(&other->v_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DoubleVector::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DoubleVector_descriptor_;
  metadata.reflection = DoubleVector_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace naothmessages

// @@protoc_insertion_point(global_scope)
