/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package de.naoth.rc.components;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Heinrich Mellmann
 */
public class SimpleProgressBar extends javax.swing.JPanel {

    private int min, max;
    private int value;
    private Color color = Color.blue;
    
    /**
     * Creates new form SimpleProgressBar
     */
    public SimpleProgressBar(int min, int max) {
        this.max = max;
        this.min = min;
        this.value = min;

        initComponents();
        
        this.textLabel.setText("");
    }
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs);
        Graphics2D g2d = (Graphics2D) grphcs;

        int width = (getWidth()*(value-min))/(max - min);
        int height = getHeight();
        g2d.setColor(color);
        if(height > 3) {
            g2d.fillRect(0, 1, width, height-2);
        } else {
            g2d.fillRect(0, 0, width, height);
        }
    }
    
    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        if (value <= max && value >= min) {
            this.value = value;
            repaint();
        }
    }

    public void setColor(Color c) {
        color = c;
    }

    public void setMaximum(int max) {
        this.max = max;
    }

    public void setMinimum(int min) {
        this.min = min;
    }
    
    public void setString(String text) {
        this.textLabel.setText(text);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        textLabel.setText("jLabel1");
        add(textLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
