/**
 * @author <a href="xu:mellmann@informatik.hu-berlin.de">Xu, Yuan</a>
 */
package de.hu_berlin.informatik.ki.nao.dialogs;

import de.hu_berlin.informatik.ki.nao.Dialog;
import de.hu_berlin.informatik.ki.nao.Helper;
import de.hu_berlin.informatik.ki.nao.Main;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

public class ConnectionManager extends javax.swing.JPanel
        implements Dialog
{

  private Main parent;
  private Properties config;
  private JFileChooser fileChooser = new JFileChooser();
  private JToggleButton[] jToggleButtons = new JToggleButton[11];
  final private String confKey = "ConnectionManagerConf";

  /** Creates new form ConnectionManager */
  public ConnectionManager()
  {
    initComponents();

    jToggleButtons[0] = jToggleButton1;
    jToggleButtons[1] = jToggleButton2;
    jToggleButtons[2] = jToggleButton3;
    jToggleButtons[3] = jToggleButton4;
    jToggleButtons[4] = jToggleButton5;
    jToggleButtons[5] = jToggleButton6;
    jToggleButtons[6] = jToggleButton7;
    jToggleButtons[7] = jToggleButton8;
    jToggleButtons[8] = jToggleButton9;
    jToggleButtons[9] = jToggleButton10;
    jToggleButtons[10] = jToggleButton11;

    ActionListener al = new ActionListener()
    {

      public void actionPerformed(ActionEvent e)
      {
        JToggleButton bt = getActiveButton(e.getSource());
        if (bt != null)
        {
          if (bt.isSelected())
          {
            for (JToggleButton button : jToggleButtons)
            {
              button.setSelected(false);
            }
            connect(Integer.parseInt(bt.getText()));
          } else
          {
            disconnect();
          }

          bt.setSelected(isConnected());
        }
      }
    };

    for (JToggleButton button : jToggleButtons)
    {
      button.addActionListener(al);
    }

    jLabelConfigFileName.setText("config/connection/nao.wlan.cfg");
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jToolBar1 = new javax.swing.JToolBar();
    jToggleButton1 = new javax.swing.JToggleButton();
    jToggleButton2 = new javax.swing.JToggleButton();
    jToggleButton3 = new javax.swing.JToggleButton();
    jToggleButton4 = new javax.swing.JToggleButton();
    jToggleButton5 = new javax.swing.JToggleButton();
    jToggleButton6 = new javax.swing.JToggleButton();
    jToggleButton7 = new javax.swing.JToggleButton();
    jToggleButton8 = new javax.swing.JToggleButton();
    jToggleButton9 = new javax.swing.JToggleButton();
    jToggleButton10 = new javax.swing.JToggleButton();
    jToggleButton11 = new javax.swing.JToggleButton();
    jButtonOpen = new javax.swing.JButton();
    jLabelConfigFileName = new javax.swing.JLabel();

    jToolBar1.setRollover(true);

    jToggleButton1.setText("1");
    jToggleButton1.setFocusable(false);
    jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton1);

    jToggleButton2.setText("2");
    jToggleButton2.setFocusable(false);
    jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton2);

    jToggleButton3.setText("3");
    jToggleButton3.setFocusable(false);
    jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton3);

    jToggleButton4.setText("4");
    jToggleButton4.setFocusable(false);
    jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton4);

    jToggleButton5.setText("5");
    jToggleButton5.setFocusable(false);
    jToggleButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton5);

    jToggleButton6.setText("6");
    jToggleButton6.setFocusable(false);
    jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton6);

    jToggleButton7.setText("7");
    jToggleButton7.setFocusable(false);
    jToggleButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton7);

    jToggleButton8.setText("8");
    jToggleButton8.setFocusable(false);
    jToggleButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton8);

    jToggleButton9.setText("9");
    jToggleButton9.setFocusable(false);
    jToggleButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton9);

    jToggleButton10.setText("10");
    jToggleButton10.setFocusable(false);
    jToggleButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton10);

    jToggleButton11.setText("11");
    jToggleButton11.setFocusable(false);
    jToggleButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton11);

    jButtonOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Open24.gif"))); // NOI18N
    jButtonOpen.setFocusable(false);
    jButtonOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButtonOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonOpenActionPerformed(evt);
      }
    });
    jToolBar1.add(jButtonOpen);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jLabelConfigFileName)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelConfigFileName)
        .addContainerGap(269, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonOpenActionPerformed
  {//GEN-HEADEREND:event_jButtonOpenActionPerformed
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION)
    {
      try
      {
        String fileName = fileChooser.getSelectedFile().getCanonicalPath();
        open(fileName);
      } catch (IOException ex)
      {
        Helper.handleException(ex);
        jLabelConfigFileName.setForeground(Color.red);
      }
    }
  }//GEN-LAST:event_jButtonOpenActionPerformed

  private void open(String fileName) throws IOException
  {
    jLabelConfigFileName.setText(fileName);
    config = new Properties();
    config.load(new FileInputStream(fileName));

    Set<String> robots = config.stringPropertyNames();
    for (JToggleButton button : jToggleButtons)
    {
      boolean ok = robots.contains("robot"+button.getText());
      button.setEnabled( ok );
    }

    jLabelConfigFileName.setForeground(Color.green);
    parent.getConfig().setProperty(confKey, fileName);
  }

  private void connect(int num)
  {
    String val = config.getProperty("robot" + num);
    String[] vals = val.split(":");
    parent.connect(vals[0], Integer.parseInt(vals[1]));
  }

  private void disconnect()
  {
    parent.disconnect();
  }

  private boolean isConnected()
  {
    return parent.getMessageServer().isConnected();
  }

  private JToggleButton getActiveButton(Object src)
  {
    for (JToggleButton button : jToggleButtons)
    {
      if (src.equals(button))
      {
        return button;
      }
    }
    return null;
  }

  public void init(Main parent)
  {
    this.parent = parent;
    String defaultConfName = parent.getConfig().getProperty(confKey, jLabelConfigFileName.getText());
    try
    {
      open(defaultConfName);
    } catch (IOException ex)
    {
      jLabelConfigFileName.setForeground(Color.red);
    }
  }

  public JPanel getPanel()
  {
    return this;
  }

  public void dispose()
  {
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonOpen;
  private javax.swing.JLabel jLabelConfigFileName;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JToggleButton jToggleButton10;
  private javax.swing.JToggleButton jToggleButton11;
  private javax.swing.JToggleButton jToggleButton2;
  private javax.swing.JToggleButton jToggleButton3;
  private javax.swing.JToggleButton jToggleButton4;
  private javax.swing.JToggleButton jToggleButton5;
  private javax.swing.JToggleButton jToggleButton6;
  private javax.swing.JToggleButton jToggleButton7;
  private javax.swing.JToggleButton jToggleButton8;
  private javax.swing.JToggleButton jToggleButton9;
  private javax.swing.JToolBar jToolBar1;
  // End of variables declaration//GEN-END:variables
}
