// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraMatrix.proto

package de.hu_berlin.informatik.ki.nao.messages;

public final class CameraMatrixMsg {
  private CameraMatrixMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CameraMatrix extends
      com.google.protobuf.GeneratedMessage {
    // Use CameraMatrix.newBuilder() to construct.
    private CameraMatrix() {
      initFields();
    }
    private CameraMatrix(boolean noInit) {}
    
    private static final CameraMatrix defaultInstance;
    public static CameraMatrix getDefaultInstance() {
      return defaultInstance;
    }
    
    public CameraMatrix getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.internal_static_naothmessages_CameraMatrix_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.internal_static_naothmessages_CameraMatrix_fieldAccessorTable;
    }
    
    // required .naothmessages.Pose3D pose = 1;
    public static final int POSE_FIELD_NUMBER = 1;
    private boolean hasPose;
    private de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D pose_;
    public boolean hasPose() { return hasPose; }
    public de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D getPose() { return pose_; }
    
    private void initFields() {
      pose_ = de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasPose) return false;
      if (!getPose().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPose()) {
        output.writeMessage(1, getPose());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPose()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPose());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix result;
      
      // Construct using de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix();
        return builder;
      }
      
      protected de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix.getDescriptor();
      }
      
      public de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix getDefaultInstanceForType() {
        return de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix) {
          return mergeFrom((de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix other) {
        if (other == de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix.getDefaultInstance()) return this;
        if (other.hasPose()) {
          mergePose(other.getPose());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D.Builder subBuilder = de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D.newBuilder();
              if (hasPose()) {
                subBuilder.mergeFrom(getPose());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPose(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required .naothmessages.Pose3D pose = 1;
      public boolean hasPose() {
        return result.hasPose();
      }
      public de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D getPose() {
        return result.getPose();
      }
      public Builder setPose(de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPose = true;
        result.pose_ = value;
        return this;
      }
      public Builder setPose(de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D.Builder builderForValue) {
        result.hasPose = true;
        result.pose_ = builderForValue.build();
        return this;
      }
      public Builder mergePose(de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D value) {
        if (result.hasPose() &&
            result.pose_ != de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D.getDefaultInstance()) {
          result.pose_ =
            de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D.newBuilder(result.pose_).mergeFrom(value).buildPartial();
        } else {
          result.pose_ = value;
        }
        result.hasPose = true;
        return this;
      }
      public Builder clearPose() {
        result.hasPose = false;
        result.pose_ = de.hu_berlin.informatik.ki.nao.messages.CommonTypes.Pose3D.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:naothmessages.CameraMatrix)
    }
    
    static {
      defaultInstance = new CameraMatrix(true);
      de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:naothmessages.CameraMatrix)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_naothmessages_CameraMatrix_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_naothmessages_CameraMatrix_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CameraMatrix.proto\022\rnaothmessages\032\021Com" +
      "monTypes.proto\"3\n\014CameraMatrix\022#\n\004pose\030\001" +
      " \002(\0132\025.naothmessages.Pose3DB:\n\'de.hu_ber" +
      "lin.informatik.ki.nao.messagesB\017CameraMa" +
      "trixMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_naothmessages_CameraMatrix_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_naothmessages_CameraMatrix_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_naothmessages_CameraMatrix_descriptor,
              new java.lang.String[] { "Pose", },
              de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix.class,
              de.hu_berlin.informatik.ki.nao.messages.CameraMatrixMsg.CameraMatrix.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          de.hu_berlin.informatik.ki.nao.messages.CommonTypes.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
