/*
 * ParameterPanel.java
 *
 * Created on 17. Juli 2008, 21:21
 */
package de.naoth.rc.dialogs;

import de.naoth.rc.RobotControl;
import de.naoth.rc.core.dialog.AbstractDialog;
import de.naoth.rc.core.dialog.DialogPlugin;
import de.naoth.rc.core.manager.ObjectListener;
import de.naoth.rc.core.manager.SwingCommandExecutor;
import de.naoth.rc.server.Command;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.xeoh.plugins.base.annotations.PluginImplementation;
import net.xeoh.plugins.base.annotations.injections.InjectPlugin;

/**
 *
 * @author  Heinrich Mellmann
 */
public class ParameterPanel extends AbstractDialog
{

  @PluginImplementation
  public static class Plugin extends DialogPlugin<ParameterPanel>
  {
    @InjectPlugin
    public static RobotControl parent;
    @InjectPlugin
    public static SwingCommandExecutor commandExecutor;
  }

  //needed to synchronize the update procedure
  private final ArrayList<ParameterListItem> parameterLists = new ArrayList<ParameterListItem>();
  // number of sources which already performed ther update
  private int updateSources = 0;
  private final int EXPECTED_SOURCES = 2;
  
  public ParameterPanel()
  {
    initComponents();
	
    jTextArea.addKeyListener(new KeyAdapter()
    {

      @Override
      public void keyPressed(KeyEvent e)
      {
        int key = e.getKeyCode();
        if (key == KeyEvent.VK_ENTER)
        {
          sendParameters();
          
          int k = jTextArea.getCaretPosition();
          if(k > 0) {
            jTextArea.setCaretPosition(k-1);
          }
        }
      }
    });
  }//end constructor

    private void updateParameterLists() 
    {
        updateSources++;

        if (updateSources == EXPECTED_SOURCES) {
            
            ParameterListItem selectedList = null;
            if (cbParameterId.getSelectedItem() != null) {
                selectedList = (ParameterListItem) cbParameterId.getSelectedItem();
            }
            
            DefaultComboBoxModel boxModel = new DefaultComboBoxModel();
            for (ParameterListItem i : parameterLists) {
                boxModel.addElement(i);
            }
            
            this.cbParameterId.setModel(boxModel);
            
            if(selectedList != null) {
                this.cbParameterId.setSelectedItem(selectedList);
            } else {
                this.cbParameterId.setSelectedIndex(0);
            }
            
            parameterLists.clear();
            updateSources = 0;
            
            System.out.println(selectedList);
        }
    }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcSaveParametersDialog = new de.naoth.rc.components.ExtendedFileChooser();
        popupMenu = new javax.swing.JPopupMenu();
        miSaveAll = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButtonList = new javax.swing.JToggleButton();
        cbParameterId = new javax.swing.JComboBox();
        jToggleButtonRefresh = new javax.swing.JToggleButton();
        jButtonSend = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSave = new javax.swing.JButton();
        btnPopupMenu = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        fcSaveParametersDialog.setAcceptAllFileFilterUsed(false);
        fcSaveParametersDialog.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fcSaveParametersDialog.setDialogTitle("Save configuration");
        fcSaveParametersDialog.setFileFilter(new FileNameExtensionFilter("Config files (*.cfg)", "cfg"));
        fcSaveParametersDialog.setSelectedFile(new java.io.File("/home/philipp/.cfg"));

        popupMenu.setInvoker(btnPopupMenu);
        popupMenu.setLabel("asdf");
        popupMenu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                popupMenuPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        miSaveAll.setText("Save all");
        miSaveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveAllActionPerformed(evt);
            }
        });
        popupMenu.add(miSaveAll);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jToggleButtonList.setText("update");
        jToggleButtonList.setFocusable(false);
        jToggleButtonList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonListActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButtonList);

        cbParameterId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbParameterIdActionPerformed(evt);
            }
        });
        jToolBar1.add(cbParameterId);

        jToggleButtonRefresh.setText("Get");
        jToggleButtonRefresh.setFocusable(false);
        jToggleButtonRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButtonRefresh);

        jButtonSend.setText("Set");
        jButtonSend.setFocusable(false);
        jButtonSend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSend.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSend);
        jToolBar1.add(jSeparator1);

        btnSave.setText("Save");
        btnSave.setToolTipText("Saving current configuration.");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnPopupMenu.setText("▼");
        btnPopupMenu.setFocusable(false);
        btnPopupMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPopupMenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPopupMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopupMenuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPopupMenu);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jToggleButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRefreshActionPerformed
  if (jToggleButtonRefresh.isSelected())
  {
    getParameterList();
  }
}//GEN-LAST:event_jToggleButtonRefreshActionPerformed

private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
  sendParameters();
}//GEN-LAST:event_jButtonSendActionPerformed

private void cbParameterIdActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbParameterIdActionPerformed
{//GEN-HEADEREND:event_cbParameterIdActionPerformed
    getParameterList();
}//GEN-LAST:event_cbParameterIdActionPerformed

private void jToggleButtonListActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButtonListActionPerformed
{//GEN-HEADEREND:event_jToggleButtonListActionPerformed
    listParameters();
}//GEN-LAST:event_jToggleButtonListActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(cbParameterId.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "You have to choose a parameter configuration!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // get parameter item
            ParameterListItem pli = ((ParameterListItem) cbParameterId.getSelectedItem());
            // set config file to the name of the parameter item
            fcSaveParametersDialog.setSelectedFile(new java.io.File(pli.name + ".cfg"));
            fcSaveParametersDialog.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fcSaveParametersDialog.setAcceptAllFileFilterUsed(false);
            fcSaveParametersDialog.setDialogTitle("Save configuration ("+pli.toString()+")");
            fcSaveParametersDialog.setFileFilter(new FileNameExtensionFilter("Config files (*.cfg)", "cfg"));
            // show save dialog
            if(fcSaveParametersDialog.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                // TODO: check if file is writeable
                // if selected file has a file extension - use this, otherwise append ".cfg" to the filename
                File f = (fcSaveParametersDialog.getSelectedFile().getName().lastIndexOf(".") == -1) ? 
                    new File(fcSaveParametersDialog.getSelectedFile()+".cfg") : 
                    fcSaveParametersDialog.getSelectedFile();
                try {
                    BufferedWriter bf = new BufferedWriter(new FileWriter(f));
                    bf.write("["+pli.name+"]");
                    bf.newLine();
                    for (Map.Entry<String, String> cfg : this.getText().entrySet()) {
                        bf.write(cfg.getKey() + "=" + cfg.getValue());
                        bf.newLine();
                    }
                    bf.close();
                } catch (IOException ex) {
                    Logger.getLogger(ParameterPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPopupMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopupMenuActionPerformed
        popupMenu.show(this.btnPopupMenu, 0, this.btnPopupMenu.getHeight());
    }//GEN-LAST:event_btnPopupMenuActionPerformed

    private void popupMenuPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_popupMenuPopupMenuWillBecomeInvisible
        this.btnPopupMenu.setSelected(false);
    }//GEN-LAST:event_popupMenuPopupMenuWillBecomeInvisible

    private void miSaveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveAllActionPerformed
        fcSaveParametersDialog.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fcSaveParametersDialog.setAcceptAllFileFilterUsed(true);
        fcSaveParametersDialog.setDialogTitle("Save configuration (All)");
        fcSaveParametersDialog.resetChoosableFileFilters();
        if(fcSaveParametersDialog.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            // TODO: check if file is writeable
            // if selected file has a file extension - use this, otherwise append ".cfg" to the filename
            File d = fcSaveParametersDialog.getSelectedFile();
            if(d.isDirectory()) {
                // TODO: ask to overwrite all existing files!?
                int oldIdx = cbParameterId.getSelectedIndex();

                // iterate over all listed parameter configurations
                int n = cbParameterId.getItemCount();
                String errors = "";
                for (int i = 0; i < n; i++) {
                    ParameterListItem next = (ParameterListItem) cbParameterId.getItemAt(i);
                    Plugin.commandExecutor.executeCommand(new ParameterListHandlerGet(), next.getCommandGET());
                    if(!this.writeParameterConfig(next, new File(d.getPath()+File.separator+next.owner+"_"+next.name+".cfg"))) {
                        errors += next.name + "\n";
                    }
                }
                // show error(s), if one/some occurred
                if(errors.compareTo("") != 0) {
                    JOptionPane.showMessageDialog(null, "Error(s) occurred: "+errors, "Error", JOptionPane.ERROR_MESSAGE);
                }

                // reset view (old status)
                cbParameterId.setSelectedIndex(oldIdx);
                this.getParameterList();

            } else {
                JOptionPane.showMessageDialog(null, "The selected file is not a directory!", "Not a directory", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_miSaveAllActionPerformed

    private HashMap<String,String> getText() {
        HashMap<String, String> result = new HashMap();
        String text = this.jTextArea.getText();
        text = text.replaceAll("( |\t)+", "");
        String[] lines = text.split("(\n)+");
        for (String l : lines) {
            String[] splitted = l.split("=");
            if (splitted.length == 2) {
                String key = splitted[0].trim();
                String value = splitted[1].trim();
                // remove the last ;
                if (value.charAt(value.length() - 1) == ';') {
                    value = value.substring(0, value.length() - 1);
                }
                result.put(key, value);
            }
        }//end for
        return result;
    }
    
    private boolean writeParameterConfig(ParameterListItem p, File f) {
        try {
            BufferedWriter bf = new BufferedWriter(new FileWriter(f));
            bf.write("["+p.name+"]");
            bf.newLine();
            for (Map.Entry<String, String> cfg : this.getText().entrySet()) {
                bf.write(cfg.getKey() + "=" + cfg.getValue());
                bf.newLine();
            }
            bf.close();
            return true;
        } catch (IOException ex) {
            Logger.getLogger(ParameterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
  private class ParameterListItem
  {
      public final String owner;
      public final String name;
      
      public ParameterListItem(String owner, String name)
      {
          this.owner = owner;
          this.name = name;
      }
      
      Command getCommandGET() {
          return new Command(owner + ":ParameterList:get")
                  .addArg("<name>", name);
      }
      
      Command getCommandSET() {
          return new Command(owner + ":ParameterList:set")
                  .addArg("<name>", name);
      }
      
      @Override
      public String toString() 
      {
          return "[" + owner + "] " + name;
      }

      @Override
      public boolean equals(Object obj) {
        if(obj instanceof ParameterListItem) {
            ParameterListItem other = (ParameterListItem)obj;
            return owner.equals(other.owner) && name.equals(other.name);
        }
        return false;
      }
  }

  class ParameterListHandlerGet implements ObjectListener<byte[]>
  {
    @Override
    public void newObjectReceived(byte[] object)
    {
        // remember the carret
        int k = jTextArea.getCaretPosition();
        jTextArea.setText(new String(object));
        try {
            jTextArea.setCaretPosition(k);
        } catch(IllegalArgumentException ex) {
            // do nothing
            // could not set the caret at the right place, e.g.,
            // if the text is shorter now
        }
        jToggleButtonRefresh.setSelected(false);
    }
    
    @Override
    public void errorOccured(String cause)
    {
      dispose();
    }
  }
  
  class ParameterListHandlerSet implements ObjectListener<byte[]>
  {
    @Override
    public void newObjectReceived(byte[] object)
    {
        // do nothing
    }
    
    @Override
    public void errorOccured(String cause)
    {
      dispose();
    }
  }
  
  class ParameterListHandlerList implements ObjectListener<byte[]>
  {
    private final String owner;
    
    public ParameterListHandlerList(String owner)
    {
        this.owner = owner;
    }
    
    @Override
    public void newObjectReceived(byte[] object)
    {
        String strResult = new String(object);
        
        String[] parameterListNames = strResult.split("\n");
        for (String name : parameterListNames) {
          parameterLists.add(new ParameterListItem(owner, name));
        }
        
        jToggleButtonList.setSelected(false);
        updateParameterLists();
    }
    
    @Override
    public void errorOccured(String cause)
    {
      dispose();
    }
  }


private void sendParameters()
{
  if (Plugin.parent.checkConnected())
  {
    Command cmd = ((ParameterListItem) cbParameterId.getSelectedItem()).getCommandSET();
    for (Map.Entry<String, String> cfg : this.getText().entrySet()) {
        cmd.addArg(cfg.getKey(), cfg.getValue());
    }
    
    Plugin.commandExecutor.executeCommand(new ParameterListHandlerSet(), cmd);
    
    // update everything
    //listParameters();
    
    // this is better, but less robust
    getParameterList();
  }
  else
  {
    jToggleButtonRefresh.setSelected(false);
  }
}

private void listParameters()
{
    if (Plugin.parent.checkConnected())
    {
      Plugin.commandExecutor.executeCommand(new ParameterListHandlerList("Cognition"), new Command("Cognition:ParameterList:list"));
      Plugin.commandExecutor.executeCommand(new ParameterListHandlerList("Motion"), new Command("Motion:ParameterList:list"));
    }
    else
    {
      jToggleButtonList.setSelected(false);
    }
}//end listParameters

  private void getParameterList()
  {
    System.out.println("test");
    if (Plugin.parent.checkConnected())
    {
      if (cbParameterId.getSelectedItem() != null)
      {
        Command cmd = ((ParameterListItem) cbParameterId.getSelectedItem()).getCommandGET();
        Plugin.commandExecutor.executeCommand(new ParameterListHandlerGet(), cmd);
      }
    }
    else
    {
      jToggleButtonRefresh.setSelected(false);
    }
  }//end refresh

  @Override
  public void dispose()
  {
    System.out.println("Dispose is not implemented for: " + this.getClass().getName());
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnPopupMenu;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbParameterId;
    private de.naoth.rc.components.ExtendedFileChooser fcSaveParametersDialog;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JToggleButton jToggleButtonList;
    private javax.swing.JToggleButton jToggleButtonRefresh;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem miSaveAll;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
