/*
 */
package naoscp.components;

import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import naoscp.tools.usb.LinuxUSBStorageDeviceManager;
import naoscp.tools.usb.OSXUSBStorageDeviceManager;
import naoscp.tools.usb.USBStorageDevice;
import naoscp.tools.usb.USBStorageDeviceManager;
import naoscp.tools.usb.WindowsUSBStorageDeviceManager;

/**
 *
 * @author Robert Martin
 */
public class USBPanel extends javax.swing.JPanel {

    private USBStorageDevice selectedUSBStorageDevice = null;

    private USBStorageDeviceManager usbStorageDeviceManager;
    
    private JFileChooser fileChooser = null;

    /**
     * Creates new form USBPanel
     */
    public USBPanel() {
        initComponents();
        
        String os = System.getProperty("os.name");

        if (os.startsWith("Linux")) {
            this.usbStorageDeviceManager = new LinuxUSBStorageDeviceManager();
            
        } else if (os.startsWith("Windows")) {
            this.usbStorageDeviceManager = new WindowsUSBStorageDeviceManager();
         
        } else if (os.contains("OS X")) {
            this.usbStorageDeviceManager = new OSXUSBStorageDeviceManager();
            
        } else {
            this.setVisible(false);
        }

    }

    public boolean hasSelection() {
        return this.selectedUSBStorageDevice != null;
    }

    public String getUSBPath() {
        if (this.hasSelection()) {
            return this.selectedUSBStorageDevice.getMountPoint();
        }
        return null;
    }

    public void closeUSBStorageDevice() {
        if (this.hasSelection()) {
            this.usbStorageDeviceManager.unmount(this.selectedUSBStorageDevice);

            //this.refresh();
        }
    }

    public boolean refresh() {
        this.usbSelectBox.removeAllItems();

        List<USBStorageDevice> usbStorageDevices = usbStorageDeviceManager.getUSBStorageDevices();

        if (usbStorageDevices.isEmpty()) {
            Logger.getGlobal().log(Level.WARNING, "Couldn't find any USB storage device!");
            this.usbSelectBox.setEnabled(false);
            this.tippLabel.setText("Couldn't find any USB storage device!");
            this.tippLabel.setForeground(new java.awt.Color(255, 51, 51));
            return false;
        } else {
            for (USBStorageDevice usbStorageDevice : usbStorageDeviceManager.getUSBStorageDevices()) {
                this.usbSelectBox.addItem(usbStorageDevice);
            }
            return true;
        }
    }
    
    public void addFileChooser(JFileChooser fileChooser){
        this.fileChooser = fileChooser;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usbSelectBox = new javax.swing.JComboBox<>();
        tippLabel = new javax.swing.JLabel();

        usbSelectBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usbSelectBoxActionPerformed(evt);
            }
        });

        tippLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tippLabel.setText("Select the deploy stick:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tippLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usbSelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tippLabel)
                .addComponent(usbSelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usbSelectBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usbSelectBoxActionPerformed
        this.selectedUSBStorageDevice = (USBStorageDevice) this.usbSelectBox.getSelectedItem();
        
        if(this.fileChooser != null) {
            this.fileChooser.setCurrentDirectory(new File(this.selectedUSBStorageDevice.getMountPoint()));
        }
    }//GEN-LAST:event_usbSelectBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel tippLabel;
    private javax.swing.JComboBox<USBStorageDevice> usbSelectBox;
    // End of variables declaration//GEN-END:variables
}
