#
# build the image:
#       docker build -t simspark-appimage -f Dockerfile_AppImage .
# create the container:
#       docker run -it -v "/path/to/save/result/:/root/Simspark.Dist" --name simspark-appimage simspark-appimage
# restart the container:
#       docker start -ia simspark-appimage
#

FROM ubuntu:18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    libfreetype6 libode6 libsdl1.2debian ruby libdevil1c2 qt4-default nano file \
    libboost-regex1.65.1 libboost-system1.65.1 libboost-thread1.65.1 \
    g++ cmake git libfreetype6-dev libode-dev libsdl-dev ruby-dev libdevil-dev libboost-dev libboost-thread-dev libboost-regex-dev libboost-system-dev libqt4-opengl-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ADD https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage /root
RUN chmod +x /root/appimagetool-x86_64.AppImage

RUN git clone https://github.com/BerlinUnited/SimSpark-SPL.git /root/Simspark.Git

COPY create_appimage.sh /root/

WORKDIR /root
ENTRYPOINT ["/root/create_appimage.sh"]
