/*
 * JointControl.java
 *
 * Created on 15. März 2008, 23:11
 */

package de.naoth.me.controls.motionneteditor;

import de.naoth.me.core.Joint;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
//import javax.swing.JOptionPane;

/**
 *
 * @author  sven
 */
public class JointControl extends javax.swing.JPanel {
    
    private Joint joint;
    
    /** Creates new form JointControl */
    public JointControl() {
        initComponents();
        jSliderJointValue.setMajorTickSpacing(10);
    }
    
    public JointControl(Joint joint){
        this(   joint.getId(), 
                joint.getMinValue(), 
                joint.getMaxValue(),
                joint.getValue());//Degrees());
        
        this.joint = joint;
    }
    
    public JointControl(String jointName, double minValue, double maxValue, double currentValue){
        
        if(!(minValue <= currentValue && currentValue <= maxValue))
        {
//         JOptionPane.showMessageDialog(null,
//            "Error : Wert ausserhalb der Grenzen: " + jointName + " " + minValue + " <= " + currentValue + " <= " + maxValue,
//            "Error", JOptionPane.ERROR_MESSAGE);
          if(currentValue < minValue)
          {
            currentValue = minValue;
          }
          if(currentValue > maxValue)
          {
            currentValue = maxValue;
          }
         }
        initComponents();
        
//        this.jLabelJointName.setText(jointName);
        this.jChkJointName.setLabel(jointName);
        this.jChkJointName.setState(true);
        this.jLabelMinValue.setText(String.valueOf(minValue));
        this.jLabelMaxValue.setText(String.valueOf(maxValue));

        this.jSliderJointValue.setMinimum((int) Math.round(minValue * 100));
        this.jSliderJointValue.setMaximum((int) Math.round(maxValue * 100));
        this.jSliderJointValue.setValue((int) Math.round(currentValue * 100));
        //this.jSliderJointValue.setMajorTickSpacing(maxValue - minValue);
        //this.jSliderJointValue.setPaintLabels(true);
        
        this.jSliderJointValue.addChangeListener(new ChangeListener()
        {
            public void stateChanged(ChangeEvent e)
            {
                double value = Math.round(jSliderJointValue.getValue() / 100);
                jSpinnerJointValue.setValue(value);
//                joint.setDegrees(value);
                joint.setValue(value);
            }
        });
        
        SpinnerNumberModel model = new SpinnerNumberModel(currentValue, minValue, maxValue, 1);
        this.jSpinnerJointValue.setModel(model);
        this.jSpinnerJointValue.setValue(currentValue);

        this.jSpinnerJointValue.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                double value = (Double) jSpinnerJointValue.getValue();
                jSliderJointValue.setValue((int) Math.round(value * 100));
                //joint.setDegrees(value);
                joint.setValue(value);
            }
        });
        
        //this.jSpinnerJointValue.setMinimum(minValue);
        //this.jSpinnerJointValue.setMaximum(maxValue);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSpinnerJointValue = new javax.swing.JSpinner();
    jLabelMinValue = new javax.swing.JLabel();
    jSliderJointValue = new javax.swing.JSlider();
    jLabelMaxValue = new javax.swing.JLabel();
    jChkJointName = new java.awt.Checkbox();

    setToolTipText("Name of a Robots Joint/Motor");
    setPreferredSize(new java.awt.Dimension(441, 40));

    jSpinnerJointValue.setPreferredSize(new java.awt.Dimension(50, 18));
    jSpinnerJointValue.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        jSpinnerJointValuePropertyChange(evt);
      }
    });

    jLabelMinValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelMinValue.setText("minVal");
    jLabelMinValue.setPreferredSize(new java.awt.Dimension(36, 14));

    jSliderJointValue.setMajorTickSpacing(100);
    jSliderJointValue.addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentHidden(java.awt.event.ComponentEvent evt) {
        jSliderJointValueComponentHidden(evt);
      }
    });

    jLabelMaxValue.setText("maxVal");

    jChkJointName.setFont(new java.awt.Font("Tahoma", 0, 11));
    jChkJointName.setLabel("joint");
    jChkJointName.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        jChkJointNameItemStateChanged(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jChkJointName, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSpinnerJointValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelMinValue, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSliderJointValue, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelMaxValue)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabelMinValue, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
            .addComponent(jSpinnerJointValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jSliderJointValue, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
          .addComponent(jLabelMaxValue, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jChkJointName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10)))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jSliderJointValueComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jSliderJointValueComponentHidden
    // TODO add your handling code here:
  }//GEN-LAST:event_jSliderJointValueComponentHidden

  private void jSpinnerJointValuePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinnerJointValuePropertyChange
    double value = (Double) jSpinnerJointValue.getValue();
    jSliderJointValue.setValue((int) Math.round(value * 100));
    joint.setValid(jChkJointName.getState());
    joint.setValue(value);
  }//GEN-LAST:event_jSpinnerJointValuePropertyChange

  private void jChkJointNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jChkJointNameItemStateChanged
    joint.setValid(jChkJointName.getState());
  }//GEN-LAST:event_jChkJointNameItemStateChanged
    
    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private java.awt.Checkbox jChkJointName;
  private javax.swing.JLabel jLabelMaxValue;
  private javax.swing.JLabel jLabelMinValue;
  private javax.swing.JSlider jSliderJointValue;
  private javax.swing.JSpinner jSpinnerJointValue;
  // End of variables declaration//GEN-END:variables
    
}
